import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ruki Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='relative w-full h-screen overflow-hidden bg-gradient-to-r from-purple-200 to-purple-800'>
        {/* <Navbar /> */}
      </div>




    </div>
  )
}

export default Home
